### ISSUE TITLE
favicon.ico file

### ISSUE THREAD

**Issue by BaseMax** [POSSF/POSSF#1]
[2020-12-11 17:13:25] ERROR `/favicon.ico' not found.

**Comment by jbampton** [comment]
`bundle exec jekyll serve`

```
  Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
[2021-07-07 08:04:42] ERROR `/favicon.ico' not found.
```

**Comment by BaseMax** [comment]
https://possf.ir/favicon.ico

Solved. https://github.com/POSSF/POSSF/commit/36e8f90be12388055e09ed01aa2533a14eed62fd https://github.com/POSSF/POSSF/commit/41dcddf1467b7a45ffdd2e3d8a4f608596fed426
