### ISSUE TITLE
Typo & translate

### ISSUE THREAD

**Issue by alefvanoon** [POSSF/POSSF#19]
![image](https://user-images.githubusercontent.com/53198048/124666256-11d85c80-deae-11eb-8ae1-15c7313a8c2a.png)
صفحه‌ی اول اشکالات متعددی از نظر غلط املایی و... دارد.
اهداف،‌ حامیان و برگزار کنندگان همایش نیز به طور مشخص یا حداقل واضح قابل رویت نیستند.

**Comment by BaseMax** [comment]
Fixed.

Thanks
