### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by alefvanoon** [POSSF/POSSF#21]
به نظرم لایسنس این مخزن هرچه زودتر مشخص بشه. تا بلاتکلیفی ایجاد نکنه.

**Comment by jbampton** [comment]
Google translate:

"I think the license of this tank should be determined as soon as possible. So as not to create uncertainty."

**Comment by BaseMax** [comment]
Hi alef;
This is more of a collective movement and we need to decide about that by the community.
The template is coded by me and will improve by the Web team.

What do you think about the license? GPL 3 is fine in this case? @alefvanoon

**Comment by alefvanoon** [comment]
Hi @BaseMax
Yes, GPL-3 is great.

**Comment by BaseMax** [comment]
Thank you for your comment.

As the first move, I added the license file at https://github.com/POSSF/POSSF/commit/6c7e5ee6c98f32db62983e0fba4650f1de26e818.

**Comment by BaseMax** [comment]
**Just to clarify:** Our plan is to start the event on the first day of October and celebrate the winners at end of the October.
We may hold some lectures and meetings in the days of October.
The effort is to provide **special prizes** for those who participate.

What do you think about the time?

By the way, The new website will be launch next days.

**Comment by BaseMax** [comment]
**Update:** I invited you, I would like to see you on the members, network list.

It's a public community, every person who stars this repository will invite to the org automatically. (We wrote some Actions for that to be auto)

**Comment by alefvanoon** [comment]
> **Just to clarify:** Our plan is to start the event on the first day of October and celebrate the winners at end of the October.
> We may hold some lectures and meetings in the days of October.
> The effort is to provide **special prizes** for those who participate.

Great!

> What do you think about the time?

Time for meetings? I will check Calendar and create new issue for it.

> By the way, The new website will be launch next days.

Good job!
