### ISSUE TITLE
FAQ Page: open/close questions

### ISSUE THREAD

**Issue by BaseMax** [POSSF/POSSF#3]
صفحه سوالات متداول سوالات باید وقتی روش کلیک میشه یا روی ایکن اونها کلیک میشه. بصورت آکاردوونی باز و بسته بشه. با افکت
down/up
 (با جاوا اسکریپت خام هم میشه نوشت / چون نیازی نیست و دلیلی نیست فقط برای این یک مورد فایل جکوئری اضافه کنیم)

**Comment by jbampton** [comment]
Google translate:

"Frequently Asked Questions page should be when the method is clicked or the icon is clicked. Open and close as an accordion. With effects
down / up
(It can also be written with raw JavaScript / because there is no need and no reason to just add a jQuery file for this case"

**Comment by BaseMax** [comment]
Already done by me in the script.js file.
So close this ISSUE
