### ISSUE TITLE
Team Page: style need

### ISSUE THREAD

**Issue by BaseMax** [POSSF/POSSF#4]
سلام صفحه تیم الان استایل نداره. باید مطابق قالب قبلی استایل بگیره. (در نظر بگیرید که توی این قالب بوت استرپ نداریم پس  
media query 
ها دستی نوشته بشه. ولی کار سختی نیست.
مشابه: https://basemax.github.io/POSSF

**Comment by jbampton** [comment]
Google translate:

"Hi, the team page does not have style now. It should be styled according to the previous template. (Consider that we do not have a bootstrap in this template
media query
Be handwritten. But it is not a difficult task.
Similar: https://basemax.github.io/POSSF"

**Comment by BaseMax** [comment]
Already done.
